/*
 * FocusPanel.java
 *
 * Created on 31 de enero de 2002, 12:09
 */


/**
 *
 * @author  Administrador
 * @version 
 */

package devices.drivers.camera.cameragui;

import devices.drivers.camera.*;

public class FocusPanel extends javax.swing.JPanel {

     private Camera port;
     
    /** Creates new form FocusPanel */
    public FocusPanel(Camera port) {
        this.port = port;
        initComponents ();
        AddItemsComboBoxs();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
//        setLayout(null);
        setLayout(new java.awt.FlowLayout());
        setBorder(new javax.swing.border.TitledBorder("Control Focus"));
        
        jButton1.setText("NEAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        }
        );
        
        add(jButton1);
//        jButton1.setLocation(4, 21);
//        jButton1.setSize(jButton1.getPreferredSize());
        
        
        jButton2.setText("FAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        }
        );
        

  //      jButton2.setLocation(207, 25);
//        jButton2.setSize(jButton2.getPreferredSize());
        
        
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        }
        );
        
        add(jComboBox1);
        jComboBox1.setBounds(89, 22, 99, 34);
        add(jButton2);        
    }//GEN-END:initComponents

  private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
// Add your handling code here:
      port.send(Comandos.FCS);
  }//GEN-LAST:event_jButton2MouseReleased

  private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
// Add your handling code here:
      port.send(Comandos.FCF);
  }//GEN-LAST:event_jButton2MousePressed

  private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
// Add your handling code here:
		port.send(Comandos.FCS);
  }//GEN-LAST:event_jButton1MouseReleased

  private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
// Add your handling code here:
      port.send(Comandos.FCN);
  }//GEN-LAST:event_jButton1MousePressed

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// Add your handling code here:
      Comando comando = (Comando) jComboBox1.getSelectedItem();
      if (!comando.equals(Comandos.FCM))
      {
      	port.send(comando);
      }
      if (comando.equals(Comandos.FCA)) 
      {
          jButton1.setEnabled(false);
          jButton2.setEnabled(false);
      }
      else 
      {
          jButton1.setEnabled(true);
          jButton2.setEnabled(true);
      }
  }//GEN-LAST:event_jComboBox1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JComboBox jComboBox1;
  // End of variables declaration//GEN-END:variables

    private void AddItemsComboBoxs() {
        jComboBox1.addItem(Comandos.FCA);
        jComboBox1.addItem(Comandos.FCM);
    }
}
