/*
 * IrisPanel.java
 *
 * Created on 31 de enero de 2002, 18:57
 */


/**
 *
 * @author  Administrador
 * @version
 */

package devices.drivers.camera.cameragui;

import devices.drivers.camera.*;

public class GainPanel extends javax.swing.JPanel {
    
    private Camera port;
    
    /** Creates new form GainPanel */
    public GainPanel(Camera port) {
        this.port = port;
        initComponents ();
        AddItemsComboBoxs();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jSlider1 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
   javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        
//        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
jPanel1.setLayout(new java.awt.FlowLayout());
		setLayout(new javax.swing.BoxLayout(this,javax.swing.BoxLayout.Y_AXIS));
        
        setBorder(new javax.swing.border.TitledBorder("Control Ganacia"));
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setMinimum(-30);
        jSlider1.setMajorTickSpacing(5);
        jSlider1.setMaximum(30);
        jSlider1.setValue(0);
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });
        
//        add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 35, -1, -1));
        
  //      jButton1.setFont(new java.awt.Font("Dialog", 1, 24));
        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
//        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
        
  //      jButton2.setFont(new java.awt.Font("Dialog", 1, 24));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        
//        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));
        
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        
  //      add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 33, -1, -1));
  		add(jComboBox1);
  		jPanel1.add(jButton1);
  		jPanel1.add(jSlider1);
  		jPanel1.add(jButton2);
  		add(jPanel1);
        
    }//GEN-END:initComponents
    
  private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
      // Add your handling code here:
      port.send(Comandos.GNMX,jSlider1.getValue());
  }//GEN-LAST:event_jSlider1MouseReleased
  
  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // Add your handling code here:
      port.send(Comandos.GNU);
      jSlider1.setValue(jSlider1.getValue()+1);
  }//GEN-LAST:event_jButton2ActionPerformed
  
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // Add your handling code here:
      port.send(Comandos.GND);
      jSlider1.setValue(jSlider1.getValue()-1);
  }//GEN-LAST:event_jButton1ActionPerformed
  
  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      // Add your handling code here:
      Comando comando = (Comando) jComboBox1.getSelectedItem();
     port.send(comando);
       if (comando.equals(Comandos.GNM)) {
          jSlider1.setEnabled(true);
          jButton1.setEnabled(true);
          jButton2.setEnabled(true);
      }
      else {
          jSlider1.setEnabled(false);
          jButton1.setEnabled(false);
          jButton2.setEnabled(false);
      }
  }//GEN-LAST:event_jComboBox1ActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JSlider jSlider1;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JComboBox jComboBox1;
  // End of variables declaration//GEN-END:variables
    
    
    private void AddItemsComboBoxs() {
        jComboBox1.addItem(Comandos.GNA);
        jComboBox1.addItem(Comandos.GNM);
    }
}
