/*
 * PLLVPanel.java
 *
 * Created on 1 de febrero de 2002, 14:03
 */

/**
 *
 * @author  diego
 */

package devices.drivers.camera.cameragui;

import devices.drivers.camera.*;

public class PLLVPanel extends javax.swing.JPanel {

    private Camera port;

    
    /** Creates new form PLLVPanel */
    public PLLVPanel(Camera port) {
        this.port = port;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jSlider1 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        
//        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
		setLayout(new java.awt.FlowLayout());
        
        setBorder(new javax.swing.border.TitledBorder("Control PLL Shift V"));
        jSlider1.setPaintLabels(true);
        jSlider1.setMaximum(624);
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });
        
//        add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));
        
//        jButton1.setFont(new java.awt.Font("Dialog", 1, 24));
        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
  //      add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        
//        jButton2.setFont(new java.awt.Font("Dialog", 1, 24));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        
//        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));
		add(jButton1);
		add(jSlider1);
		add(jButton2);
        
    }//GEN-END:initComponents

    private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
        // Add your handling code here:
      port.send(Comandos.PV,jSlider1.getValue());
    }//GEN-LAST:event_jSlider1MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
      port.send(Comandos.PVU);
      jSlider1.setValue(jSlider1.getValue()+1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
      port.send(Comandos.PVD);
      jSlider1.setValue(jSlider1.getValue()-1);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

}
