/*
 * WBPanel.java
 *
 * Created on 31 de enero de 2002, 12:31
 */


/**
 *
 * @author  Administrador
 * @version 
 */

package devices.drivers.camera.cameragui;

import devices.drivers.camera.*;

public class WBPanel extends javax.swing.JPanel {

     private Camera port;
     
    /** Creates new form WBPanel */
    public WBPanel(Camera port) {
        this.port = port;
        initComponents ();
        AddItemsComboBoxs();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSlider3 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSlider4 = new javax.swing.JSlider();
		setLayout (new javax.swing.BoxLayout(this,javax.swing.BoxLayout.Y_AXIS));
//        setLayout(null);
        setBorder(new javax.swing.border.TitledBorder("Control White Balance"));
        
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        }
        );
        
        add(jComboBox1);
  //      jComboBox1.setLocation(12, 35);
//        jComboBox1.setSize(jComboBox1.getPreferredSize());
        
        
  		jPanel1.setLayout(new java.awt.FlowLayout());
//        jPanel1.setLayout(null);
        jPanel1.setBorder(new javax.swing.border.TitledBorder("Red"));
        
  //      jButton5.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton5.setText("-");
          jButton5.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton5ActionPerformed(evt);
              }
          }
          );
          jPanel1.add(jButton5);
//          jButton5.setLocation(10, 25);
//          jButton5.setSize(jButton5.getPreferredSize());
          
          
  //      jButton6.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton6.setText("+");
          jButton6.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton6ActionPerformed(evt);
              }
          }
          );
  
    //      jButton6.setLocation(277, 24);
//          jButton6.setSize(jButton6.getPreferredSize());
          
          
        jSlider3.setMinorTickSpacing(1);
          jSlider3.setMajorTickSpacing(10);
          jSlider3.setMaximum(255);
          jSlider3.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseReleased(java.awt.event.MouseEvent evt) {
                  jSlider3MouseReleased(evt);
              }
          }
          );
          jPanel1.add(jSlider3);
  //        jSlider3.setLocation(64, 41);
//          jSlider3.setSize(jSlider3.getPreferredSize());
          jPanel1.add(jButton6);        
          
        add(jPanel1);
        jPanel1.setBounds(170, 20, 348, 86);
        
        
    	jPanel2.setLayout(new java.awt.FlowLayout());
//        jPanel2.setLayout(null);
        jPanel2.setBorder(new javax.swing.border.TitledBorder("Blue"));
        
//        jButton7.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton7.setText("-");
          jButton7.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton7ActionPerformed(evt);
              }
          }
          );
          jPanel2.add(jButton7);
//          jButton7.setLocation(10, 17);
//          jButton7.setSize(jButton7.getPreferredSize());
          
          
//        jButton8.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton8.setText("+");
          jButton8.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton8ActionPerformed(evt);
              }
          }
          );

  //        jButton8.setLocation(281, 15);
    //      jButton8.setSize(jButton8.getPreferredSize());
          
          
        jSlider4.setMinorTickSpacing(1);
          jSlider4.setMajorTickSpacing(10);
          jSlider4.setMaximum(255);
          jSlider4.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseReleased(java.awt.event.MouseEvent evt) {
                  jSlider4MouseReleased(evt);
              }
          }
          );
          jPanel2.add(jSlider4);
          jPanel2.add(jButton8);
//          jSlider4.setLocation(65, 31);
//          jSlider4.setSize(jSlider4.getPreferredSize());
          
          
        add(jPanel2);
        jPanel2.setBounds(170, 126, 349, 89);
        
    }//GEN-END:initComponents

  private void jSlider4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider4MouseReleased
// Add your handling code here:
      port.send(Comandos.WBB,jSlider4.getValue());
  }//GEN-LAST:event_jSlider4MouseReleased

  private void jSlider3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider3MouseReleased
// Add your handling code here:
      port.send(Comandos.WBR,jSlider3.getValue());
  }//GEN-LAST:event_jSlider3MouseReleased

  private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// Add your handling code here:
      port.send(Comandos.WBBU);
      jSlider4.setValue(jSlider4.getValue()+1);
  }//GEN-LAST:event_jButton8ActionPerformed

  private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// Add your handling code here:
      port.send(Comandos.WBBD);
      jSlider4.setValue(jSlider4.getValue()-1);
  }//GEN-LAST:event_jButton7ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// Add your handling code here:
      port.send(Comandos.WBRU);
      jSlider3.setValue(jSlider3.getValue()+1);
  }//GEN-LAST:event_jButton6ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// Add your handling code here:
      port.send(Comandos.WBRD);
      jSlider3.setValue(jSlider3.getValue()-1);
  }//GEN-LAST:event_jButton5ActionPerformed

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// Add your handling code here:
      Comando comando = (Comando) jComboBox1.getSelectedItem();
      port.send(comando);
      if (comando.equals(Comandos.WBM)) {
          jSlider3.setEnabled(true);
          jSlider4.setEnabled(true);
          jButton5.setEnabled(true);
          jButton6.setEnabled(true);
          jButton7.setEnabled(true);
          jButton8.setEnabled(true);
      }
      else {
          jSlider3.setEnabled(false);
          jSlider4.setEnabled(false);
          jButton5.setEnabled(false);
          jButton6.setEnabled(false);
          jButton7.setEnabled(false);
          jButton8.setEnabled(false);
      }
  }//GEN-LAST:event_jComboBox1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JSlider jSlider3;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JSlider jSlider4;
  // End of variables declaration//GEN-END:variables

    private void AddItemsComboBoxs() {
        jComboBox1.addItem(Comandos.WBA);
        jComboBox1.addItem(Comandos.WBI);
        jComboBox1.addItem(Comandos.WBO);
        jComboBox1.addItem(Comandos.WBF);
        jComboBox1.addItem(Comandos.WBM);
    }
}
