/*
 * AWBPanel.java
 *
 * Created on 31 de enero de 2002, 20:21
 */


/**
 *
 * @author  Administrador
 * @version 
 */

package devices.drivers.camera.cameragui;

import devices.drivers.camera.*;

public class AWBPanel extends javax.swing.JPanel {

     private Camera port;

    
    /** Creates new form AWBPanel */
    public AWBPanel(Camera port) {
        this.port = port;
        initComponents ();
        AddItemsComboBoxs();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jComboBox1 = new javax.swing.JComboBox();
  //      setLayout(null);
  setLayout(new java.awt.FlowLayout());
        setBorder(new javax.swing.border.TitledBorder("Control AWB Speed"));
        
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        }
        );
        
        add(jComboBox1);
//        jComboBox1.setLocation(49, 28);
//        jComboBox1.setSize(jComboBox1.getPreferredSize());
        
    }//GEN-END:initComponents

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// Add your handling code here:
      Comando comando = (Comando) jComboBox1.getSelectedItem();
      port.send(comando);
  }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables

     private void AddItemsComboBoxs() {
        jComboBox1.addItem(Comandos.AWF);
        jComboBox1.addItem(Comandos.AWM);
        jComboBox1.addItem(Comandos.AWS);
        jComboBox1.addItem(Comandos.AWV);
    }
}
