/*
 * BLPanel.java
 *
 * Created on 31 de enero de 2002, 18:38
 */


/**
 *
 * @author  Administrador
 * @version 
 */

package devices.drivers.camera.cameragui;

import devices.drivers.camera.*;

public class BLPanel extends javax.swing.JPanel {

     private Camera port;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bldown;
    private javax.swing.JButton blup;
    private javax.swing.JSlider blslider;
    private javax.swing.JCheckBox blon;
	private javax.swing.JPanel  upPanel;
	private javax.swing.JPanel  downPanel;
    // End of variables declaration//GEN-END:variables

    
    /** Creates new form BLPanel */
    public BLPanel(Camera port) {
        this.port = port;
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        bldown = new javax.swing.JButton();
        blup = new javax.swing.JButton();
        blslider = new javax.swing.JSlider();
        blon = new javax.swing.JCheckBox();
		upPanel = new javax.swing.JPanel();
		downPanel = new javax.swing.JPanel();

		setLayout(new javax.swing.BoxLayout(this,javax.swing.BoxLayout.Y_AXIS));
		downPanel.setLayout(new java.awt.FlowLayout());
        setBorder(new javax.swing.border.TitledBorder("Control Back Light"));
        
        bldown.setText("-");
        bldown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldownActionPerformed(evt);
            }
        }
        );
        
        blup.setText("+");
        blup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blupActionPerformed(evt);
            }
        }
        );
        
        blslider.setMinorTickSpacing(1);
        blslider.setMinimum(-30);
        blslider.setMajorTickSpacing(5);
        blslider.setMaximum(30);
        blslider.setValue(0);
        blslider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                blsliderMouseReleased(evt);
            }
        }
        );

		blon.setText("Activate back light comp.");
		blon.setSelected(false);
        blon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blonActionPerformed(evt);
            }
        });
		
		boolean addDownPanel=false;
		if (port.isAvaiable(Comandos.BLD))
		{
	        downPanel.add(bldown);       
			addDownPanel=true;
	    }
	    if (port.isAvaiable(Comandos.BL))
	    {	    
	        downPanel.add(blslider);
			addDownPanel=true;
	    }
		if (port.isAvaiable(Comandos.BLU))
		{
	        downPanel.add(blup);
			addDownPanel=true;
		}
	    if (port.isAvaiable(Comandos.BLO))
	    {
	    	upPanel.add(blon);
	    	this.add(upPanel);
	    }
		if (addDownPanel)
		    this.add(downPanel);
    }//GEN-END:initComponents

  private void blupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// Add your handling code here:
      port.send(Comandos.BLU);
      blslider.setValue(blslider.getValue()+1);
  }//GEN-LAST:event_jButton2ActionPerformed

  private void bldownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Add your handling code here:
      port.send(Comandos.BLD);
      blslider.setValue(blslider.getValue()-1);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void blsliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
// Add your handling code here:
      port.send(Comandos.BL,blslider.getValue());
  }//GEN-LAST:event_jSlider1MouseReleased

  private void blonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Add your handling code here:
	  if (blon.isSelected())
	      port.send(Comandos.BLO);
	  else
		  port.send(Comandos.BLF);
  }//GEN-LAST:event_jButton1ActionPerformed

}
