/*
 * ColorPanel.java
 *
 * Created on 31 de enero de 2002, 19:38
 */


/**
 *
 * @author  Administrador
 * @version 
 */

package devices.drivers.camera.cameragui;

import devices.drivers.camera.*;

public class ColorPanel extends javax.swing.JPanel {

      private Camera port;
    
    /** Creates new form ColorPanel */
    public ColorPanel(Camera port) {
        this.port = port;
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSlider2 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSlider3 = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSlider4 = new javax.swing.JSlider();
        setLayout(new javax.swing.BoxLayout(this, 1));
        setBorder(new javax.swing.border.TitledBorder("Control Color"));
        
//        jPanel1.setLayout(null);
		jPanel1.setLayout(new java.awt.FlowLayout());
        jPanel1.setBorder(new javax.swing.border.TitledBorder("Red Gain"));
        
//        jButton1.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton1.setText("-");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton1ActionPerformed(evt);
              }
          }
          );
          jPanel1.add(jButton1);
//          jButton1.setLocation(25, 22);
//          jButton1.setSize(jButton1.getPreferredSize());
          
          
//        jButton2.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton2.setText("+");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton2ActionPerformed(evt);
              }
          }
          );
//          jPanel1.add(jButton2);
//          jButton2.setLocation(293, 15);
//          jButton2.setSize(jButton2.getPreferredSize());
          
          
        jSlider1.setMinimum(-30);
          jSlider1.setMaximum(30);
          jSlider1.setValue(0);
          jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseReleased(java.awt.event.MouseEvent evt) {
                  jSlider1MouseReleased(evt);
              }
          }
          );
          jPanel1.add(jSlider1);
  //        jSlider1.setLocation(86, 34);
//          jSlider1.setSize(jSlider1.getPreferredSize());
          jPanel1.add(jButton2);        
          
        add(jPanel1);
        
        
//        jPanel2.setLayout(null);
        jPanel2.setBorder(new javax.swing.border.TitledBorder("Blue Gain"));
  		jPanel2.setLayout(new java.awt.FlowLayout());      
//        jButton3.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton3.setText("-");
          jButton3.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton3ActionPerformed(evt);
              }
          }
          );
          jPanel2.add(jButton3);
//          jButton3.setLocation(27, 32);
//          jButton3.setSize(jButton3.getPreferredSize());
          
          
//        jButton4.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton4.setText("+");
          jButton4.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton4ActionPerformed(evt);
              }
          }
          );
//          jPanel2.add(jButton4);
//          jButton4.setLocation(302, 32);
//          jButton4.setSize(jButton4.getPreferredSize());
          
          
        jSlider2.setMinimum(-30);
          jSlider2.setMaximum(30);
          jSlider2.setValue(0);
          jSlider2.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseReleased(java.awt.event.MouseEvent evt) {
                  jSlider2MouseReleased(evt);
              }
          }
          );
          jPanel2.add(jSlider2);
//          jSlider2.setLocation(82, 44);
//          jSlider2.setSize(jSlider2.getPreferredSize());
          jPanel2.add(jButton4);
          
        add(jPanel2);
        
        
//        jPanel3.setLayout(null);
        jPanel3.setBorder(new javax.swing.border.TitledBorder("Red Hue"));
   		jPanel3.setLayout(new java.awt.FlowLayout());            
//        jButton5.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton5.setText("-");
          jButton5.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton5ActionPerformed(evt);
              }
          }
          );
          jPanel3.add(jButton5);
  //        jButton5.setLocation(30, 17);
//          jButton5.setSize(jButton5.getPreferredSize());
          
          
//        jButton6.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton6.setText("+");
          jButton6.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton6ActionPerformed(evt);
              }
          }
          );
//          jPanel3.add(jButton6);
//          jButton6.setLocation(307, 23);
//          jButton6.setSize(jButton6.getPreferredSize());
          
          
        jSlider3.setMinimum(-30);
          jSlider3.setMaximum(30);
          jSlider3.setValue(0);
          jSlider3.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseReleased(java.awt.event.MouseEvent evt) {
                  jSlider3MouseReleased(evt);
              }
          }
          );
          jPanel3.add(jSlider3);
          jSlider3.setLocation(89, 30);
          jSlider3.setSize(jSlider3.getPreferredSize());
          
        jPanel3.add(jButton6);                
        add(jPanel3);

        
//        jPanel4.setLayout(null);
        jPanel4.setBorder(new javax.swing.border.TitledBorder("Blue Hue"));
   		jPanel4.setLayout(new java.awt.FlowLayout());                    
  //      jButton7.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton7.setText("-");
          jButton7.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton7ActionPerformed(evt);
              }
          }
          );
          jPanel4.add(jButton7);
//          jButton7.setLocation(31, 22);
//          jButton7.setSize(jButton7.getPreferredSize());
          
          
//        jButton8.setFont(new java.awt.Font ("Dialog", 1, 24));
          jButton8.setText("+");
          jButton8.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton8ActionPerformed(evt);
              }
          }
          );
          jPanel4.add(jButton8);
  //        jButton8.setLocation(306, 25);
//          jButton8.setSize(jButton8.getPreferredSize());
          
          
        jSlider4.setMinimum(-30);
          jSlider4.setMaximum(30);
          jSlider4.setValue(0);
          jSlider4.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseReleased(java.awt.event.MouseEvent evt) {
                  jSlider4MouseReleased(evt);
              }
          }
          );
          jPanel4.add(jSlider4);
//          jSlider4.setLocation(88, 39);
//          jSlider4.setSize(jSlider4.getPreferredSize());
          
          jPanel4.add(jButton8);          
        add(jPanel4);
        
    }//GEN-END:initComponents

  private void jSlider4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider4MouseReleased
// Add your handling code here:
      port.send(Comandos.BH,jSlider4.getValue());
  }//GEN-LAST:event_jSlider4MouseReleased

  private void jSlider3MouseReleased(java.awt.event.MouseEvent evt) 
  {
  //GEN-FIRST:event_jSlider3MouseReleased
// Add your handling code here:
      port.send(Comandos.RH,jSlider3.getValue());
  }//GEN-LAST:event_jSlider3MouseReleased

  private void jSlider2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider2MouseReleased
// Add your handling code here:
      port.send(Comandos.BG,jSlider2.getValue());
  }//GEN-LAST:event_jSlider2MouseReleased

  private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
// Add your handling code here:
     port.send(Comandos.RG,jSlider1.getValue());
  }//GEN-LAST:event_jSlider1MouseReleased

  
  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// Add your handling code here:
      port.send(Comandos.BGU);
      jSlider2.setValue(jSlider2.getValue()+1);
  }//GEN-LAST:event_jButton4ActionPerformed

  private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// Add your handling code here:
      port.send(Comandos.BHD);
      jSlider4.setValue(jSlider4.getValue()-1);
  }//GEN-LAST:event_jButton7ActionPerformed

  private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// Add your handling code here:
      port.send(Comandos.BHU);
      jSlider4.setValue(jSlider4.getValue()+1);
  }//GEN-LAST:event_jButton8ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// Add your handling code here:
      port.send(Comandos.RHD);
      jSlider3.setValue(jSlider3.getValue()-1);
  }//GEN-LAST:event_jButton5ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// Add your handling code here:
      port.send(Comandos.RHU);
      jSlider3.setValue(jSlider3.getValue()+1);
  }//GEN-LAST:event_jButton6ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// Add your handling code here:
      port.send(Comandos.BGD);
      jSlider2.setValue(jSlider2.getValue()-1);
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Add your handling code here:
      port.send(Comandos.RGD);
      jSlider1.setValue(jSlider1.getValue()-1);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// Add your handling code here:
      port.send(Comandos.RGU);
      jSlider1.setValue(jSlider1.getValue()+1);
  }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JSlider jSlider4;
    // End of variables declaration//GEN-END:variables

}
