/*
 * DetailPanel.java
 *
 * Created on 31 de enero de 2002, 19:33
 */


/**
 *
 * @author  Administrador
 * @version
 */

package devices.drivers.camera.cameragui;

import devices.drivers.camera.*;

public class DetailPanel extends javax.swing.JPanel {
    
    private Camera port;
    
    /** Creates new form DetailPanel */
    public DetailPanel(Camera port) {
        this.port = port;
        initComponents ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
//        setLayout(null);
        setLayout(new java.awt.FlowLayout());
        setBorder(new javax.swing.border.TitledBorder("Control Detalle"));
        
//        jButton1.setFont(new java.awt.Font ("Dialog", 1, 24));
        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        }
        );
        
        add(jButton1);
//        jButton1.setLocation(23, 38);
//        jButton1.setSize(jButton1.getPreferredSize());
        
        
//        jButton2.setFont(new java.awt.Font ("Dialog", 1, 24));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        }
        );
        

  //      jButton2.setLocation(292, 37);
//        jButton2.setSize(jButton2.getPreferredSize());
        
        
        jSlider1.setMinimum(-6);
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(9);
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        }
        );
        
        add(jSlider1);
//        jSlider1.setLocation(82, 51);
//        jSlider1.setSize(jSlider1.getPreferredSize());
        add(jButton2);        
    }//GEN-END:initComponents
    
  private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
      // Add your handling code here:
      port.send(Comandos.DT,jSlider1.getValue());
  }//GEN-LAST:event_jSlider1MouseReleased
  
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // Add your handling code here:
      port.send(Comandos.DTD);
      jSlider1.setValue(jSlider1.getValue()-1);
  }//GEN-LAST:event_jButton1ActionPerformed
  
  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // Add your handling code here:
      port.send(Comandos.DTU);
      jSlider1.setValue(jSlider1.getValue()+1);
  }//GEN-LAST:event_jButton2ActionPerformed
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
    
}
