/*
 * PLLHPanel.java
 *
 * Created on 31 de enero de 2002, 20:45
 */


/**
 *
 * @author  Administrador
 * @version 
 */

package devices.drivers.camera.cameragui;

import devices.drivers.camera.*;

public class PLLHPanel extends javax.swing.JPanel {

    private Camera port;
    
    /** Creates new form PLLHPanel */
    public PLLHPanel(Camera port) {
        this.port = port;
        initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        
//        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
		setLayout(new java.awt.FlowLayout());
        
        setBorder(new javax.swing.border.TitledBorder("Control PLL Shift H"));
//        jButton1.setFont(new java.awt.Font("Dialog", 1, 24));
        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
		add(jButton1);
//        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        
//        jButton2.setFont(new java.awt.Font("Dialog", 1, 24));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        

//        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));
        
        jSlider1.setMajorTickSpacing(40);
        jSlider1.setMaximum(453);
        jSlider1.setValue(200);
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });
        
//        add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 210, 30));
        add(jSlider1);
		add(jButton2);        
    }//GEN-END:initComponents

    private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
        // Add your handling code here:
      port.send(Comandos.PH,jSlider1.getValue());
    }//GEN-LAST:event_jSlider1MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
      port.send(Comandos.PHU);
      jSlider1.setValue(jSlider1.getValue()+1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
      port.send(Comandos.PHD);
      jSlider1.setValue(jSlider1.getValue()-1);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

}
