/*
 * (c) 2000-2002 Humberto Martinez
 */

package wucore.gui;

import java.awt.*;
import java.io.*;
import javax.swing.*;

import ptolemy.plot.*;

public class PlotWindow extends JFrame
{
	static public int				POINTS		= 50;
	static public final int			OFFSET		= 50;
	static public final int			WIDTH		= 584;						// the plot on its own
	static public final int			HEIGHT		= 300;
	static public final int			VALUES_W	= 175;						// and what a panel of values adds to it (a third)
	static public final Color		C_VALUE		= new Color (226, 226, 226);	// the ground a value is read off
	
	static public String				PSUFFIX		= ".plot";
	static private int				counter		= 0;
	
	protected Plot					plot;
	protected ChildWindowListener		parent		= null;
	
	protected int					curx			= 0;
	protected PrintWriter				stream		= null;

	// the values of the lines, written beside the plot when they are asked for
	protected String					vtitle		= null;
	protected JPanel					vpanel		= null;
	protected JTextField[]			vfields		= null;
	
	protected PlotWindow ()
	{		
		plot	= new Plot ();
		curx	= 0;
	}
	
	public PlotWindow (String title)
	{
		this ();
		
		init_interface (title);
		this.parent = null;
		
		counter ++;
	}
	
	public PlotWindow (ChildWindowListener parent, String title)
	{
		this ();
		
		init_interface (title);
		this.parent = parent;
		
		counter ++;
	}
	
	private void init_interface (String title)
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setVisible (false);
		setTitle (title);	
		setLocation (250 + counter * OFFSET, counter * OFFSET);
		
		getContentPane ().add ("Center", plot);
		setVisible (true);
		plot.setGrid (true);
		plot.setColor (true);
		plot.setMarksStyle ("none");
		plot.setConnected (true);
		plot.setButtons (false);
		pack ();
		setSize (WIDTH, HEIGHT);
		
		//{{INIT_MENUS
		//}}
		
		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		//}}
	}
	
	public void open ()
	{
		open (null);
	}
	
	public void open (String name)
	{
		setVisible (true);

		dump_stop ();
		if (name != null)	dump_start (name + PSUFFIX, "Data Plotting");
	}
	
	public synchronized void close ()
	{
		dump_stop ();
		
		if (parent != null)
			parent.childClosed (this);
		
		setVisible (false);
		dispose ();
	}
	
	/**
	 * Asks for a panel of values beside the plot, under the title given (null
	 * asks for none, and it is built once): what every line of the plot is worth
	 * right now, as a pair of its label and its value, which a plot of impulses
	 * does not let anybody read off the picture.
	 *
	 * The window is made a third wider for it, so that the plot keeps the room it
	 * had. The values themselves are not to be typed in.
	 */
	public void setValues (String title)
	{
		JScrollPane		sp;

		if ((title == null) || (vtitle != null))		return;
		vtitle	= title;
		vpanel	= new JPanel (new GridBagLayout ());
		vpanel.setBorder (BorderFactory.createTitledBorder (title));
		sp		= new JScrollPane (vpanel, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
									ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		sp.setBorder (BorderFactory.createEmptyBorder ());
		sp.setPreferredSize (new Dimension (VALUES_W, HEIGHT));
		getContentPane ().add ("East", sp);
		setSize (getWidth () + VALUES_W, getHeight ());
		validate ();
	}

	public void setLegend (String[] labels)
	{
		int			i;
		
		plot.clearLegends ();
		for (i = 0; i < labels.length; i++)
			plot.addLegend (i, labels[i]);
		if (vpanel != null)			buildValues (labels);
	}

	/** One row per line of the plot: what it is called, and a field for its value. */
	protected void buildValues (String[] labels)
	{
		GridBagConstraints	gc = new GridBagConstraints ();

		vpanel.removeAll ();
		vfields		= new JTextField[labels.length];
		gc.insets	= new Insets (2, 4, 2, 4);
		gc.anchor	= GridBagConstraints.WEST;
		for (int i = 0; i < labels.length; i++)
		{
			JLabel		l = new JLabel (labels[i]);

			l.setFont (l.getFont ().deriveFont (Font.PLAIN, 11f));
			gc.gridx = 0;		gc.gridy = i;		gc.weightx = 0.0;
			gc.fill = GridBagConstraints.NONE;
			vpanel.add (l, gc);

			vfields[i]	= new JTextField (5);
			vfields[i].setEditable (false);							// read, not typed in
			vfields[i].setFocusable (false);
			vfields[i].setBackground (C_VALUE);
			vfields[i].setHorizontalAlignment (JTextField.RIGHT);
			vfields[i].setFont (vfields[i].getFont ().deriveFont (Font.PLAIN, 11f));
			gc.gridx = 1;		gc.weightx = 1.0;
			gc.fill = GridBagConstraints.HORIZONTAL;
			vpanel.add (vfields[i], gc);
		}
		// and a filler, so that the rows stay at the top of the panel
		gc.gridx = 0;		gc.gridy = labels.length;		gc.gridwidth = 2;
		gc.weighty = 1.0;	gc.fill = GridBagConstraints.BOTH;
		vpanel.add (new JLabel (), gc);
		vpanel.revalidate ();
		vpanel.repaint ();
	}

	/**
	 * What every line is worth, written beside the plot. Whoever draws does it
	 * from its own thread, so the fields are written on the event thread.
	 */
	protected void showValues (final double[] data)
	{
		final int		n;
		Runnable		r;

		if ((vfields == null) || (data == null))		return;
		n	= Math.min (vfields.length, data.length);
		r	= new Runnable ()
		{
			public void run ()
			{
				for (int i = 0; i < n; i++)		vfields[i].setText (String.format (java.util.Locale.US, "%.3f", data[i]));
			}
		};
		if (SwingUtilities.isEventDispatchThread ())		r.run ();
		else												SwingUtilities.invokeLater (r);
	}
	
	public void setLabels (String horiz, String vert)
	{
		plot.setXLabel (horiz);
		plot.setYLabel (vert);
	}
	
	public void setImpulses (boolean stems)
	{
		plot.setImpulses (stems);
	}
	
	public void setYRange (double ymin, double ymax)
	{
		plot.setYRange (ymin, ymax);
	}
	
	public void updateData (double[] data)
	{
		int			i;
		
		if (data == null)			return;
		
		dump_data (data);		
		
		curx ++;
		for (i = 0; i < data.length; i++)
			plot.addPoint (i, curx, data[i], true);
		
		if (curx > POINTS)		plot.setXRange ((double)  (curx - POINTS), (double) curx);
		
		plot.repaint ();
		showValues (data);
	}	
	
	public void updateData (double[][] data, int n, int m)
	{
		int			i, j;
		
		if (data == null)			return;
		
		plot.clear (false);
		for (i = 0; i < n; i++)
		{
			dump_data (data[i]);		
			for (j = 1; j < m; j++)
				plot.addPoint (j-1, data[i][0], data[i][j], true);		
		}	
		plot.setXRange (data[0][0], data[n-1][0]);	
		plot.repaint ();
	}	
	
	protected void dump_start (String name, String title)
	{
		File				file;
		
		if (name == null)			return;
		
		file = new File (name);
		try 
		{
			stream = new PrintWriter (new BufferedOutputStream (new FileOutputStream (file)));
			if (title != null)
				stream.println ("# " + title);
			stream.flush ();
		} catch (Exception e) { stream = null; }
	}
	
	protected void dump_data (double[] current)
	{
		int			i;
		
		if ((stream == null) || (current == null)) 	return;
		
		for (i = 0; i < current.length; i++)
			stream.print (current[i] +  "\t");
		
		stream.println (" ");
		stream.flush (); 
	}
	
	protected void dump_data (String[] labels)
	{
		int			i;
		
		if ((stream == null) || (labels == null)) 	return;
		
		for (i = 0; i < labels.length; i++)
			stream.print (labels[i] +  "\t");
		
		stream.println (" ");
		stream.flush (); 
	}
	
	protected void dump_stop ()
	{
		if (stream == null) return;
		
		stream.flush (); 
		stream.close (); 
		stream = null;
	}
	
	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension d = getSize();
		
		super.addNotify();
		
		if (fComponentsAdjusted)
			return;
		
		// Adjust components according to the insets
		setSize(getInsets().left + getInsets().right + d.width, getInsets().top + getInsets().bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(getInsets().left, getInsets().top);
			components[i].setLocation(p);
		}
		fComponentsAdjusted = true;
	}
	
	// Used for addNotify check.
	boolean fComponentsAdjusted = false;
	
	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == PlotWindow.this)
				PlotWindow_WindowClosing(event);
		}
	}
	
	void PlotWindow_WindowClosing(java.awt.event.WindowEvent event)
	{
		close ();
	}
}
